// CoreBattle/ClientApp/src/app/game/game.component.ts
import { Component, OnInit } from '@angular/core';
import * as Signal from '@microsoft/signalr'

@Component({
  selector: 'app-game',
  templateUrl: './game.component.html',
  styleUrls: ['./game.component.css']
})
export class GameComponent implements OnInit {

  y1;
  x1;
  isReady:boolean;
  isStart:boolean;
  myName:string;
  opName:string;
  myField: Cell[];
  enField: Cell[];
  HubConnection: Signal.HubConnection;
  StartConnection = () =>{
    this.HubConnection = new Signal.HubConnectionBuilder()
    .withUrl('/game')
    .build();

    this.HubConnection.on("ErrorHandler", (data) => {
      alert(data);
    });
    this.HubConnection.on("PlaceShipResult", (data) => {
      this.myField = data;
    });
    this.HubConnection.on("MyName", (data) => {
      this.myName = data;
    });

    this.HubConnection.on("OponentName", (data) => {
      this.opName = data;
    });
    
    this.HubConnection.on("ReadyResult", (data) => {
      if(data == "OK")
          this.isReady = true; 
    });

    this.HubConnection.on("START_GAME", () => {
      this.isStart = true;
    });

    this.HubConnection.on("EndGame", (data) => {
      alert(data);
      this.isStart = false;
    });

    this.HubConnection.on("ShootResult",  (m, en) => {
      console.log("MY",this.myField)
      this.myField = m;
      console.log("ENEMY",this.enField)
      this.enField = en;
    });

    this.HubConnection.start().then(() => console.log('Connection started'))
    .catch(err => console.log('Error while starting connection: ' + err));
    // this.HubConnection.invoke("Send", "MSG");
  }

  constructor() {
    this.isReady = false;
    this.isStart = false;
    this.StartConnection();
    this.myField = this.GetField();
    this.enField = this.GetField();
   }

  ngOnInit() {
  }

  PlaceShipClick = (x,y) => {
    if (this.x1 == null && this.y1 == null) {
        this.x1= x;
        this.y1= y;       
    }
    else {
        this.HubConnection.invoke("PlaceShip", this.x1, this.y1, x, y);
        this.x1 = null;
        this.y1 = null;
    }
  }

  ShootClick = (x, y) => {
    this.HubConnection.invoke("Shoot",x,y);
  }

  ReadyClick = () => {
    this.HubConnection.invoke("Ready");
  }

  GetField = () => {
    let field = Array<Cell>();
    for (var i = 0; i < 10; i++) {
        for (var j = 0; j < 10; j++) {
            let f = new Cell;
            f.id = this.uuidv4();
            f.x = i;
            f.y = j;
            f.state = 0
            field.push(f);
        }
    }
    return field;
  }
  CellClass(state:number,isEnemy:boolean){
    if(state == 1){
      return "battle-area-cell miss";
    }
    if(state == 2 && !isEnemy){
      return "battle-area-cell ship";
    }
    if(state == 3){
      return "battle-area-cell injured";
    }
    return "battle-area-cell";
  }
  public trackItem (index: number, item: Cell) {
    return item.id;
  }
  uuidv4() {
    return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, function(c) {
      var r = Math.random() * 16 | 0, v = c == 'x' ? r : (r & 0x3 | 0x8);
      return v.toString(16);
    });
  }
}

class Cell {
  id: string;
  x: number;
  y: number;
  state: number;
}
    <div class="row justify-content-center align-items-center player-field battle-area">
        <div class="col">
            <h2 class="centerBlock">{{myName}}</h2>
            <div class="battle-area-table centerBlock">
                <div 
                    *ngFor="let cell of myField trackBy: trackItem" 
                    (click)="isReady || PlaceShipClick(cell.x,cell.y)"
                    [ngClass]="CellClass(cell.state,false)">
                </div>
            </div>
            <input [hidden]="isReady" class="btn btn-dark centerBlock" (click)="ReadyClick()" type="submit" value="READY TO PLAY" />
        </div>
    </div>

    <div class="row justify-content-center align-items-center player-field battle-area">
        <div class="col">
            <h2 class="centerBlock">{{opName}}</h2>
            <div class="battle-area-table centerBlock">
                <div *ngFor="let cell of enField" 
                    (click)="!isStart || ShootClick(cell.x,cell.y)"
                    [ngClass]="CellClass(cell.state,true)">
                </div>
            </div>
        </div>
    </div>

// CoreBattle/React/src/components/Game.js
﻿import React, { Component } from 'react';
import { GameField } from './gameField';
import '../custom.css'
import * as signalR from "@microsoft/signalr";

export class Game extends Component {
    state = {
        myField: [],
        enemyField: [],
        hubConnection: null,
        x1: null,  
        y1: null,  
        isReady: false,
        isStart: false,
        oponentName: "___________",
        playerName: ""
    }

    componentDidMount = () => {
        let conn = new signalR.HubConnectionBuilder()
            .withUrl("/game")
            .build();

        conn.on("ErrorHandler", function (msg) {
            alert(msg);
        });

        conn.on("PlaceShipResult", (fiel) => {
            console.log(fiel);
            this.setState({
                myField: fiel
            });
        });

        conn.on("ReadyResult", (data) => {
            if (data === 'OK') {
                this.setState({
                    isReady: true
                });
            }
        });

        conn.on("MyName", (name) => {
            this.setState({
                playerName: name,
            });
        });
        conn.on("OponentName", (name) => {
            this.setState({
                oponentName: name
            });
        });

        conn.on("ShootResult", (myF, enF) => {
            this.setState({
                myField: myF,
                enemyField: enF
            });
        });

        conn.on("EndGame", (msg) => {
            alert('YOU ' + msg);
            this.setState({
                isStart: false
            });
        });

        conn.on("START_GAME", () => {
            this.setState({
                isStart: true
            });
        });

        conn.start();
        this.setState({
            hubConnection: conn
        })
    }

    GetEmptyField = () => {
        let field = [];
        for (var i = 0; i < 10; i++) {
            for (var j = 0; j < 10; j++) {
                let f = {};
                f.x = i;
                f.y = j;
                f.state = 0
                field.push(f);
            }
        }
        return field;
    }

    ReadyClick = () => {
        this.state.hubConnection.invoke("Ready");
    }

    PlaceShipClick = (x, y) => {
        if (this.state.x1 == null && this.state.y1 == null) {
            this.setState({
                x1: x,
                y1: y
            })
        }
        else {
            this.state.hubConnection.invoke("PlaceShip", this.state.x1, this.state.y1, x, y);
            this.setState({
                x1: null,
                y1: null
            })
        }
    }

    ShootClick = (x, y) => {
        this.state.hubConnection.invoke("Shoot", x, y);
    }

    render() {
        let field = this.GetEmptyField();
        if (this.state.myField.length !== 0)
            field = this.state.myField;

        let enF = this.GetEmptyField();
        if (this.state.enemyField.length !== 0)
            enF = this.state.enemyField;
        return (
            <div className="Container">
                <div className="row justify-content-center align-items-center player-field battle-area">
                    <div className="col">
                        <h2 className="centerBlock">{this.state.playerName}</h2>
                        <div className="battle-area-table centerBlock">
                            {
                                this.state.isReady && (
                                    <GameField field={field} withClick={false} isEnemy={false} />
                                ) ||
                                !this.state.isReady && (
                                    <GameField field={field} onClick={this.PlaceShipClick} withClick={true} isEnemy={false} />
                                )
                            }
                        </div>
                        {
                            !this.state.isReady && (
                                <input className="btn btn-dark" onClick={this.ReadyClick} type="submit" value="READY TO PLAY" />
                            )
                        }
                    </div>
                </div>

                <div className="row justify-content-center align-items-center enemy-field battle-area">
                    <div className="col">
                        <h2 className="centerBlock">{this.state.oponentName}</h2>
                        <div className="battle-area-table centerBlock">
                            {
                                this.state.isStart && (
                                    <GameField field={enF} withClick={true} onClick={this.ShootClick} isEnemy={true} />
                                ) ||
                                !this.state.isStart && (
                                    <GameField field={enF} withClick={false} isEnemy={true} />
                                )
                            }
                        </div>
                    </div>
                </div>
            </div>
        );
    }
}
